"""Final patch: fix all 130 remaining issues using index-based approach."""
import json, sys
sys.stdout.reconfigure(encoding='utf-8')

JSON_PATH = "app/src/main/assets/flirt_dataset.json"
with open(JSON_PATH, encoding='utf-8') as f:
    data = json.load(f)

fixed = 0

def fix(idx, tone, index, new_line):
    global fixed
    data[idx][tone][index] = new_line
    fixed += 1

fix(19, "bold", 2, "Chupiddama marchipoledu bujji real ga feel chestha! 🔥")
fix(21, "bold", 3, "Chupiddama tonight bujji near unnav ga kaladam! 😏")
fix(22, "sweet", 3, "Ayyoo sorry bujji nenu unnanu matladam open ga! 😘")
fix(27, "sweet", 4, "Nuvvu adbhutam bangaram seriously naa ki words levu! 🥰")
fix(27, "bold", 2, "Chupinchu tonight bujji ne lo unna feelings real! 🔥")
fix(28, "sweet", 1, "Same feeling bujji naaku kuda alane undhi always! 😊")
fix(30, "sweet", 4, "Gurtuchesav thanks bangaram naa gurinchi aalochisthunnav! 🥰")
fix(30, "funny", 2, "Air thinna healthy diet bujji weightloss secret cheppu! 😜")
fix(32, "sweet", 2, "Biryani baby delicious ga undha full details bujji! 💕")
fix(32, "funny", 2, "Maggi single jeevitham anthem bujji no shame! 😜")
fix(36, "bold", 1, "Ippude modalu chesanu ne kosam attention full ga! 😉")
fix(41, "sweet", 4, "Aagalekapothunna bujji super excited chala khushi! 🥰")
fix(42, "funny", 2, "I know born cute nuvvu admit chesukunnav finally! 😜")
fix(44, "sweet", 2, "Haha thanks baby nuvvu share chesav manadi song! 💕")
fix(44, "funny", 0, "Bathroom singer official ga nenu witness bujji! 😂")
fix(45, "sweet", 1, "Nuvvu gorgeous bujji nee eyes ki kaadu naa words ki! 😊")
fix(45, "sweet", 2, "Aww sweet thanks bangaram nuvvu cheppadam love avthundhi! 💕")
fix(47, "sweet", 4, "Nammu bujji please nuvve naa real hero always! 🥰")
fix(47, "bold", 2, "Abhimanam nachindhi baby real ga feel avthunnanu! 🔥")
fix(50, "funny", 0, "Vampire schedule lo unna bujji night owl official! 😂")
fix(54, "bold", 3, "Naa daggara bore avvadam impossible bujji guarantee! 😏")
fix(56, "funny", 4, "Shakespeare of hmm bujji thesis reyali nee ni! 😂")
fix(57, "sweet", 1, "Matladam inka bujji cheppu emaina undha? 😊")
fix(57, "sweet", 2, "Okay baby oka pani cheppu chestha nenu! 💕")
fix(58, "sweet", 2, "Baadha avvaku baby solve chestha kalisi together! 💕")
fix(59, "sweet", 3, "Please aapu baby nee gurinchi chala care avthunna! 😘")
fix(60, "sweet", 3, "Tension cheyaku baby nenu unnanu ne tho always! 😘")
fix(60, "bold", 4, "Stress buster nenu bujji okasari raa try chesav antav! 😘")
fix(61, "sweet", 2, "Sure bujji coming oka second matram wait cheyyi! 💕")
fix(61, "sweet", 4, "Ippude chestha bangaram wait cheyyi oka second! 🥰")
fix(62, "sweet", 4, "Ready bujji calling chestha reach chesav na! 🥰")
fix(63, "sweet", 2, "Nuvvu chesthav baby nee words chala touch chesayi! 💕")
fix(64, "funny", 4, "Legal torture office lo rozu chesth unchuthunnaraa bujji! 😂")
fix(64, "bold", 4, "Tonight bharistha aagu nenu vasthunna bujji! 😘")
fix(65, "bold", 2, "Teesukosthanu back nundi tappinchukolevu bangaram! 🔥")
fix(69, "funny", 4, "Energy drinks fake bujji nenu real source naa direct! 😂")
fix(69, "bold", 3, "Energize chestha guarantee bujji raa intiki ippude! 😏")
fix(70, "funny", 1, "Penguin la waddling chesav aa nidra matta bujji! 🤣")
fix(70, "bold", 1, "Hug best heater bujji scientifically proven real ga! 😉")
fix(74, "sweet", 4, "Enjoy bujji link pampu nenu kuda vintha! 🥰")
fix(76, "bold", 2, "Stress relief naa speciality bujji okasari try cheyyi! 🔥")
fix(78, "sweet", 3, "Already okay avthundhi bangaram nuvvu unnanduke! 😘")
fix(84, "sweet", 3, "Smart bujji nuvvu cheppav admit chestha nenu! 😘")
fix(85, "sweet", 4, "Celebrations time bangaram naa success nee valla! 🥰")
fix(86, "sweet", 2, "Party cheddama celebrate kalisi bujji eppudu? 💕")
fix(87, "sweet", 4, "Support chestha always bujji ne decision right! 🥰")
fix(87, "funny", 1, "Job hating club member bujji welcome committee ready! 🤣")
fix(89, "funny", 0, "Chivariki recognition dorikinadhi bujji long time late! 😂")
fix(91, "funny", 0, "Born comedian bujji official ga pronoun chesthunna! 😂")
fix(92, "funny", 2, "Professional teaser bujji degree undha confirm chesuko! 😜")
fix(93, "sweet", 3, "Naughty bujji kaani cute ga undhi suit avthundhi! 😘")
fix(95, "sweet", 3, "Plan cheddama kalisi bujji eppudu fix chestha! 😘")
fix(97, "sweet", 4, "Planning cutie secret bujji wait and see! 🥰")
fix(98, "sweet", 4, "kalisi celebrate andamga bujji special undhi! 🥰")
fix(98, "bold", 3, "Hot celebration planned bujji wait cheyyi! 😏")
fix(101, "sweet", 3, "Sending bujji naa love waves reach avthunnaya? 😘")
fix(102, "sweet", 1, "Soon bangaram pakka this week fix chestha! 😊")
fix(102, "sweet", 3, "Weekend fix cheddama bujji tomorrow plan? 😘")
fix(103, "sweet", 1, "Twaraga kaladam bujji nenu kuda eduru choostunna! 😊")
fix(103, "sweet", 4, "kalisi soon bangaram nuvvu vasthe bore undadu! 🥰")
fix(103, "funny", 0, "Drama king bujji award function modalu chestha! 😂")
fix(104, "funny", 4, "Surveillance expert bujji skills impressive really! 😂")
fix(106, "bold", 2, "Chupista always actions speak louder bujji! 🔥")
fix(107, "sweet", 3, "Thanks baby khushi aipoyanu ne words tho! 😘")
fix(107, "sweet", 4, "Same feeling bangaram naa dream nee vi bujji! 🥰")
fix(108, "funny", 3, "Platinum member exclusive bujji velvet rope opening! 🤭")
fix(110, "sweet", 4, "Unique connection manadi bujji enni janmaalaina! 🥰")
fix(110, "funny", 1, "Unique specimen bujji lab report interesting! 🤣")
fix(110, "funny", 4, "One of a kind bujji dictionary lo photo undhi! 😂")
fix(111, "sweet", 4, "Aagalekapothunna excited max bujji nuvvu kuda cheppu! 🥰")
fix(113, "sweet", 3, "Done eppudu bangaram morning aa evening? 😘")
fix(113, "sweet", 4, "Excited lets plan bujji full day outing! 🥰")
fix(114, "sweet", 4, "Done plan cheddaam bujji route fix cheyyi! 🥰")
fix(114, "funny", 2, "Jellyfish bodyguard kavali bujji beach plan unsafe! 😜")
fix(115, "romantic", 3, "Spiritual date special bangaram peace together devudu blessing! 💕")
fix(115, "sweet", 3, "Haa veldaam bangaram ready chestha morning early! 😘")
fix(115, "sweet", 4, "Prayer time peaceful bujji kalisi vellali! 🥰")
fix(116, "sweet", 4, "Travel mood excited bujji route plan chestha! 🥰")
fix(116, "funny", 2, "Google maps wrong turn bujji tradition avuthundhi! 😜")
fix(116, "bold", 4, "Destination honeymoon level bujji planning hot! 😘")
fix(117, "funny", 2, "Comedian retired permanent bujji contract signed aipoyindhi! 😜")
fix(117, "funny", 4, "Serious mode permanent bujji na ki avvadam ledu! 😂")
fix(119, "sweet", 3, "Sorry matladam calmly bujji cheppu em aindhi! 😘")
fix(121, "funny", 2, "Telepathy try chestha bujji signal strong ga pampukunta! 😜")
fix(121, "funny", 3, "Emoji conversation modalu cheyyi bujji creative! 🤭")
fix(122, "sweet", 3, "kalisi possible trust base ga pettdam bujji! 😘")
fix(123, "funny", 0, "Single Netflix enjoy bujji until I arrive! 😂")
fix(124, "sweet", 1, "sweet dreams bujji naa tho kalagaane bore fix! 😊")
fix(124, "sweet", 3, "Night night bujji naa thoughts tho nidra! 😘")
fix(124, "sweet", 4, "kalalu well bangaram sweet ones I hope! 🥰")
fix(124, "funny", 3, "Insomniac lifestyle proud bujji roll model unnav! 🤭")
fix(126, "sweet", 4, "sweet dreams bangaram trust chesuko nenu always! 🥰")
fix(126, "funny", 2, "Okay mom padukunta lights off bujji done! 😜")
fix(127, "romantic", 3, "kalisi healthy avdaam bujji naa tho easy! 💕")
fix(155, "romantic", 4, "Ok prema accept bujji nee ok naa oxygen! 😍")
fix(168, "sweet", 2, "Navvu healthy baby nuvvu navvina day naa best! 💕")
fix(172, "funny", 4, "Skeleton goals achieve bujji progress visible! 😂")
fix(176, "funny", 3, "Yesterday clothes same bujji laundry avoid pro! 🤭")
fix(178, "bold", 4, "Hot matching look fire couple bujji coordination goals! 😘")
fix(185, "funny", 4, "Friends bad influence bujji scapegoat ready always! 😂")
fix(203, "bold", 1, "Naa choice clear nuvve top option bangaram! 🔥")
fix(204, "funny", 4, "Nee opinion bujji approved nenu agree chestha always! 😂")
fix(206, "funny", 2, "Naa system reboot ki nuvvu valid reason bujji! 😜")
fix(207, "funny", 3, "Pelli market evaluation closed nuvve best match bangaram! 🤣")
fix(209, "funny", 0, "Miss meter limits cross aindhi bujji overloading! 😂")
fix(209, "bold", 4, "Raa tension pothundhi daggara ki bujji fast! 😉")
fix(210, "funny", 1, "Professional bore avvadam bujji second opinion kuda same! 😂")
fix(211, "funny", 1, "Genuine nuvvu bujji no doubts trust chestha! 😂")
fix(213, "funny", 4, "Reliable partner bujji trust issues aa enduku! 😂")
fix(214, "romantic", 1, "Nee side nenu undadam best gift bujji! 💕")
fix(214, "sweet", 1, "Surprise ready baby eduru choosi cheppu! 🎁")
fix(214, "funny", 2, "Budget approve chesaka order pedthunna bujji! 😜")
fix(215, "funny", 2, "App muted manually checking bujji nee ki only! 😜")
fix(215, "bold", 0, "Call compliment direct chestha nee ki special bujji! 😏")
fix(216, "funny", 4, "Google Maps wrong turn expert bujji trip ready! 😂")
fix(216, "bold", 2, "Surprise trip date ready bujji vasthav aa? 😉")
fix(218, "funny", 1, "Red carpet nee kosam ready bujji VIP treatment! 😂")
fix(218, "bold", 3, "Naa updates exclusive nee ki only baby! 😏")
fix(219, "sweet", 3, "Sweet private plans cheddaamu bujji kalisi! 🏠")
fix(219, "bold", 4, "Romance starting bujji nee tho special undhi! 😉")
fix(220, "romantic", 3, "Nee msgs naa top priority bangaram sorry late! 💗")
fix(220, "sweet", 3, "Next time instant reply chestha bangaram promise! 🌸")
fix(221, "funny", 1, "No filters needed natural beauty bujji real ga! 😂")
fix(221, "funny", 4, "Screensaver locked bujji photo update chestha! 😂")
fix(222, "funny", 0, "Bad mood exterminator bujji nenu vasthunna ippude! 😂")

print(f"\nTotal fixes applied: {fixed}")

with open(JSON_PATH, 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
print("Saved!")
